### ISSUE TITLE
Add Licence and attribution

### ISSUE THREAD

**Issue by addiittya2006** [addiittya2006/historewind#8]
Wiki attribution needs to be added for all the images and data extracted from wikipedia in the menu and at the bottom.

**Comment by ghost** [comment]
What kind of license do you want for the repo? You have selections to choose from [here](https://choosealicense.com/). Just let me know and I'll add it for you. :wink:

**Comment by addiittya2006** [comment]
Actually we want to add license and attributtion for the wikipedia data and images we are using, not for the repo itself.

**Comment by addiittya2006** [comment]
also, a UI improvement is needed for displaying the license.
